import { StyleSheet } from 'react-native';
import { C } from '../constants/colors';

export const styles = StyleSheet.create({

  // ─── Layout ────────────────────────────────────────────────────────────────
  container: { flex: 1, backgroundColor: C.bg },
  scroll:    { padding: 16, paddingBottom: 120 },
  title:     { fontSize: 22, fontWeight: '800', color: C.dark, paddingHorizontal: 16, paddingTop: 14, paddingBottom: 4 },

  // ─── NavBar ────────────────────────────────────────────────────────────────
  navBar:         { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingTop: 6, paddingBottom: 6, backgroundColor: C.bg, borderBottomWidth: 1, borderBottomColor: C.border },
  navBackBtn:     { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 6, minWidth: 70 },
  navBackArrow:   { fontSize: 28, color: C.primary, lineHeight: 32, marginTop: -2 },
  navBackLabel:   { fontSize: 15, color: C.primary, fontWeight: '600', marginLeft: 2 },
  navTitle:       { flex: 1, textAlign: 'center', fontSize: 17, fontWeight: '700', color: C.dark },
  navActionBtn:   { minWidth: 70, alignItems: 'flex-end', paddingHorizontal: 8, paddingVertical: 6 },
  inlineBackBtn:  { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 4, paddingVertical: 4, alignSelf: 'flex-start' },
  inlineBackArrow:{ fontSize: 26, color: C.primary, lineHeight: 30, marginTop: -1 },
  inlineBackLabel:{ fontSize: 15, color: C.primary, fontWeight: '600', marginLeft: 2 },
  form:      { gap: 14 },
  loader:    { marginBottom: 24 },

  // ─── Input ─────────────────────────────────────────────────────────────────
  input: {
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    backgroundColor: C.white,
    color: C.dark,
    fontSize: 15,
    fontWeight: '500',
  },
  multiline: { minHeight: 90, textAlignVertical: 'top' },

  // ─── Card ──────────────────────────────────────────────────────────────────
  card: {
    backgroundColor: C.white,
    borderRadius: 20,
    padding: 16,
    shadowColor: C.primary,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
  },
  cardHeader: { fontSize: 13, fontWeight: '800', color: C.dark, textTransform: 'uppercase', letterSpacing: 0.5 },

  // ─── Login / Register ──────────────────────────────────────────────────────
  loginWrap: { flex: 1, justifyContent: 'center', gap: 32, paddingTop: 16 },
  loginBrand: { alignItems: 'center', gap: 6 },
  loginEmoji: { fontSize: 56 },
  loginTitle: { fontSize: 36, fontWeight: '900', color: C.dark, letterSpacing: -1 },
  loginSubtitle: { fontSize: 15, color: C.textLight, fontWeight: '500' },
  loginForm: { gap: 14 },
  loginInputWrap: { gap: 6 },
  loginInputLabel: { fontSize: 13, fontWeight: '700', color: C.text, marginLeft: 2 },
  loginInput: {
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: C.white,
    color: C.dark,
    fontSize: 15,
    fontWeight: '500',
  },
  loginPasswordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 14,
    backgroundColor: C.white,
    paddingRight: 8,
  },
  passwordEyeBtn: { padding: 10 },
  passwordEyeText: { fontSize: 18 },
  registerProgressBar: { width: '100%', height: 4, backgroundColor: C.border, borderRadius: 2, marginTop: 12 },
  registerProgressFill: { height: 4, backgroundColor: C.primary, borderRadius: 2 },
  loginDivider: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  loginDividerLine: { flex: 1, height: 1, backgroundColor: C.border },
  loginDividerText: { color: C.textMuted, fontSize: 13, fontWeight: '600' },
  btnOutline: {
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: C.primary,
    backgroundColor: C.white,
  },
  btnOutlineText: { color: C.primary, fontWeight: '800', fontSize: 15, letterSpacing: 0.2 },

  // ─── Found Pet ─────────────────────────────────────────────────────────────
  foundWrap: { gap: 14, paddingTop: 8 },
  foundEmoji: { fontSize: 52, textAlign: 'center' },
  foundTitle: { fontSize: 24, fontWeight: '900', color: C.dark, textAlign: 'center' },
  foundSubtitle: { fontSize: 14, color: C.textLight, textAlign: 'center', lineHeight: 20 },
  foundPetName: { fontSize: 28, fontWeight: '900', color: C.dark, textAlign: 'center' },
  lostAlertBanner: {
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: C.warning,
  },
  lostAlertText: { color: '#92400E', fontWeight: '700', fontSize: 13 },

  // ─── Home ──────────────────────────────────────────────────────────────────
  homeHeader: {
    borderRadius: 22,
    padding: 22,
    backgroundColor: C.dark,
    marginBottom: 2,
    shadowColor: C.dark,
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 14,
    elevation: 4,
  },
  homeHeaderEyebrow: { color: C.primaryLight, fontWeight: '700', fontSize: 13, marginBottom: 6 },
  homeHeaderTitle: { color: C.white, fontSize: 30, fontWeight: '900', letterSpacing: -0.5 },
  homeHeaderSubtitle: { color: '#94A3B8', marginTop: 6, fontSize: 13, lineHeight: 18 },

  addPetCta: {
    backgroundColor: C.primary,
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: C.primary,
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 4,
  },
  addPetCtaText: { color: C.white, fontWeight: '900', fontSize: 16, letterSpacing: 0.2 },

  // Pet card en Home
  petCard: {
    backgroundColor: C.white,
    borderRadius: 20,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: C.primary,
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 2,
  },
  petCardPhotoWrap: { position: 'relative' },
  petCardPhoto: { width: 72, height: 72, borderRadius: 999 },
  petCardLostDot: {
    position: 'absolute', top: 2, right: 2,
    width: 14, height: 14, borderRadius: 7,
    backgroundColor: C.danger,
    borderWidth: 2, borderColor: C.white,
  },
  petCardName:  { fontSize: 17, fontWeight: '800', color: C.dark },
  petCardBreed: { fontSize: 13, color: C.textLight, fontWeight: '500', marginTop: 2 },
  petCardArrow: { fontSize: 22, color: C.textMuted, fontWeight: '300' },

  emptyState: { alignItems: 'center', gap: 10, paddingVertical: 32 },
  emptyStateEmoji: { fontSize: 52 },
  emptyStateTitle: { fontSize: 18, fontWeight: '800', color: C.dark },
  emptyStateHint: { fontSize: 14, color: C.textLight, textAlign: 'center', lineHeight: 20, maxWidth: 260 },

  logoutBtn: { marginTop: 4, paddingVertical: 12, alignItems: 'center' },
  logoutBtnText: { color: C.textLight, fontWeight: '600', fontSize: 14 },
  logoutWrap: { marginTop: 8, marginBottom: 14 },

  // ─── PetDetail Hero ────────────────────────────────────────────────────────
  petHero: {
    alignItems: 'center',
    paddingVertical: 20,
    backgroundColor: C.white,
    borderRadius: 24,
    shadowColor: C.primary,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 14,
    elevation: 3,
    gap: 6,
  },
  petHeroAvatarWrap: { position: 'relative' },
  petHeroAvatar: { width: 110, height: 110, borderRadius: 999 },
  petHeroCameraBtn: {
    position: 'absolute', bottom: 2, right: 2,
    backgroundColor: C.white,
    borderRadius: 14,
    width: 28, height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  petHeroName:  { fontSize: 26, fontWeight: '900', color: C.dark, marginTop: 4 },
  petHeroBreed: { fontSize: 14, color: C.textLight, fontWeight: '500' },

  // Nav grid 2x2
  navGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  navGridCard: {
    width: '47.5%',
    backgroundColor: C.white,
    borderRadius: 18,
    padding: 16,
    gap: 6,
    borderTopWidth: 3,
    shadowColor: C.primary,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 2,
  },
  navGridIcon:  { fontSize: 26 },
  navGridTitle: { fontSize: 15, fontWeight: '800', color: C.dark },
  navGridHint:  { fontSize: 12, color: C.textLight, fontWeight: '500' },

  // Keep legacy nav card keys (used nowhere now but safe to keep)
  navCard:      { backgroundColor: C.white, borderRadius: 16, padding: 14, gap: 4 },
  navCardTitle: { fontSize: 17, fontWeight: '800', color: C.dark },
  navCardHint:  { color: C.textLight, fontWeight: '600' },

  // ─── Buttons ───────────────────────────────────────────────────────────────
  btnPrimary: {
    backgroundColor: C.primary,
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: C.primary,
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 10,
    elevation: 3,
  },
  btnPrimaryText: { color: C.white, fontWeight: '800', fontSize: 15, letterSpacing: 0.2 },

  btnGhost: {
    backgroundColor: C.white,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: C.border,
  },
  btnGhostText: { color: C.dark, fontWeight: '700', fontSize: 15 },

  // Legacy action buttons (still used in vet/vaccine screens)
  actionRow: { flexDirection: 'row', gap: 10 },
  actionBtn: {
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnPrimary:     { backgroundColor: C.dark },
  actionBtnPrimaryText: { color: C.white, fontWeight: '900' },
  actionBtnGhost:       { backgroundColor: C.white, borderWidth: 1.5, borderColor: C.border },
  actionBtnGhostText:   { color: C.dark, fontWeight: '900' },

  saveBtn:     { backgroundColor: C.success },
  saveBtnText: { color: C.white, fontWeight: '900', fontSize: 15 },

  deleteBtn:     { backgroundColor: C.danger },
  deleteBtnText: { color: C.white, fontWeight: '900', fontSize: 15 },

  linkBtn:     { backgroundColor: C.primary },
  linkBtnText: { color: C.white, fontWeight: '900', fontSize: 15 },

  backBtn:     { backgroundColor: C.white, borderWidth: 1.5, borderColor: C.border },
  backBtnText: { color: C.dark, fontWeight: '900' },

  // ─── Badges ────────────────────────────────────────────────────────────────
  badge:         { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 },
  badgeText:     { fontSize: 12, fontWeight: '700' },
  badgeOk:       { backgroundColor: C.successLight },
  badgeDanger:   { backgroundColor: C.dangerLight },
  badgeTextOk:   { color: C.success },
  badgeTextDanger: { color: C.danger },

  // ─── Data rows ─────────────────────────────────────────────────────────────
  row:      { flexDirection: 'row', justifyContent: 'space-between', gap: 10, paddingVertical: 4 },
  rowLabel: { color: C.textLight, fontWeight: '600', fontSize: 14 },
  rowValue: { color: C.dark, fontWeight: '700', fontSize: 14, flexShrink: 1, textAlign: 'right' },

  switchRow:   { flexDirection: 'row', alignItems: 'center', gap: 12 },
  switchLabel: { flex: 1, color: C.text, fontWeight: '700', fontSize: 15 },

  // ─── Select / Dropdown ─────────────────────────────────────────────────────
  selectInput:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectInputText:    { color: C.dark, fontWeight: '600', fontSize: 15 },
  selectChevron:      { color: C.textLight, fontWeight: '800' },
  selectMenu:         { marginTop: 6, backgroundColor: C.white, borderWidth: 1.5, borderColor: C.border, borderRadius: 14, overflow: 'hidden' },
  selectOption:       { paddingVertical: 13, paddingHorizontal: 14 },
  selectOptionActive: { backgroundColor: C.primaryLight },
  selectOptionText:       { color: C.dark, fontWeight: '600' },
  selectOptionTextActive: { color: C.primary, fontWeight: '700' },

  // ─── Calendar ──────────────────────────────────────────────────────────────
  calendarCard:          { marginTop: 8, backgroundColor: C.white, borderWidth: 1.5, borderColor: C.border, borderRadius: 16, padding: 12 },
  calendarHeader:        { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  calendarArrowBtn:      { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: C.surface },
  calendarArrowText:     { fontSize: 18, color: C.dark, fontWeight: '700' },
  calendarMonthTitle:    { color: C.dark, fontWeight: '800', textTransform: 'capitalize' },
  calendarWeekRow:       { flexDirection: 'row', marginBottom: 6 },
  calendarWeekDay:       { flex: 1, textAlign: 'center', color: C.textLight, fontWeight: '700', fontSize: 12 },
  calendarGrid:          { flexDirection: 'row', flexWrap: 'wrap', rowGap: 6 },
  calendarDayBtn:        { width: '14.285%', aspectRatio: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 10 },
  calendarDayBtnDisabled:  { opacity: 0 },
  calendarDayBtnSelected:  { backgroundColor: C.primary },
  calendarDayText:         { color: C.dark, fontWeight: '600' },
  calendarDayTextSelected: { color: C.white, fontWeight: '800' },
  calendarInlineBtn:     { paddingVertical: 11, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1.5, borderColor: C.border, backgroundColor: C.white },
  calendarInlineBtnText: { color: C.dark, fontWeight: '700' },

  // ─── Mi Perfil ─────────────────────────────────────────────────────────────
  profileHero: {
    alignItems: 'center',
    paddingVertical: 16,
    gap: 6,
  },
  profileAvatarLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: C.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  profileAvatarLargeText: {
    fontSize: 30,
    fontWeight: '800',
    color: C.primary,
  },
  profileHeroName: {
    fontSize: 22,
    fontWeight: '800',
    color: C.dark,
    letterSpacing: -0.3,
  },
  profileHeroMeta: {
    fontSize: 13,
    color: C.textLight,
    fontWeight: '500',
  },

  // ─── Profile (legacy, still used in some places) ───────────────────────────
  homePetImageWrap: { width: 72, height: 72, borderRadius: 999, overflow: 'hidden', backgroundColor: C.surface },
  homePetImage:     { width: 72, height: 72, borderRadius: 999 },
  profileHeader:         { backgroundColor: C.white, borderRadius: 20, padding: 16, flexDirection: 'row', gap: 14, alignItems: 'center' },
  profileHeaderCompact:  { backgroundColor: C.white, borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 14 },
  avatarWrap:        { width: 92, height: 92, borderRadius: 999, overflow: 'hidden' },
  avatar:            { width: 92, height: 92, borderRadius: 999 },
  avatarPlaceholder: { backgroundColor: C.dark, alignItems: 'center', justifyContent: 'center' },
  avatarInitials:    { color: C.white, fontSize: 26, fontWeight: '800', letterSpacing: 1 },
  profileName:       { fontSize: 22, fontWeight: '800', color: C.dark },
  profileSub:        { color: C.textLight, fontSize: 14, fontWeight: '600' },
  changePhotoHint:   { color: C.primary, fontSize: 12, fontWeight: '600' },

  // ─── Form fields ───────────────────────────────────────────────────────────
  fieldLabel:       { color: C.text, fontWeight: '700', marginBottom: 4, fontSize: 13 },
  labeledInlineRow: { flexDirection: 'row', gap: 10, alignItems: 'stretch' },
  leftTitleBox:     { width: 130, borderWidth: 1.5, borderColor: C.border, borderRadius: 12, backgroundColor: C.surface, justifyContent: 'center', paddingHorizontal: 10 },
  leftTitleText:    { color: C.text, fontWeight: '800', fontSize: 13 },
  inlineValueInput: { flex: 1, marginBottom: 0 },
  sectionBlockTitle:{ color: C.text, fontWeight: '800', marginTop: 2 },
  largeBlockInput:  { minHeight: 96 },

  // ─── Reference photos ──────────────────────────────────────────────────────
  referencePhotosRow: { flexDirection: 'row', gap: 10 },
  referencePhotoBox:  { flex: 1, minHeight: 84, borderWidth: 1.5, borderColor: C.border, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: C.surface },
  referencePhotoText: { color: C.textLight, fontWeight: '700', fontSize: 13 },

  // ─── Symptoms ──────────────────────────────────────────────────────────────
  symptomInputRow:  { flexDirection: 'row', gap: 8, alignItems: 'center' },
  symptomInput:     { flex: 1 },
  symptomChipsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  symptomChip:      { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 999, backgroundColor: C.primaryLight },
  symptomChipText:  { color: C.primary, fontWeight: '700', fontSize: 13 },

  // ─── Attachments ───────────────────────────────────────────────────────────
  attachmentBtnsRow:     { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  smallInlineBtn:        { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1.5, borderColor: C.border, backgroundColor: C.white },
  smallInlineBtnText:    { color: C.dark, fontWeight: '800', fontSize: 13 },
  attachmentChip:        { borderWidth: 1.5, borderColor: C.border, borderRadius: 12, paddingVertical: 8, paddingHorizontal: 10, backgroundColor: C.surface },
  attachmentChipText:    { color: C.text, fontWeight: '700', fontSize: 13 },
  attachmentEditChip:    { borderWidth: 1.5, borderColor: C.border, borderRadius: 12, paddingVertical: 8, paddingHorizontal: 10, backgroundColor: C.surface, flexDirection: 'row', alignItems: 'center', gap: 8 },
  removeAttachmentBtn:   { backgroundColor: C.dangerLight, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  removeAttachmentBtnText: { color: C.danger, fontWeight: '800', fontSize: 12 },

  // ─── Vet history ───────────────────────────────────────────────────────────
  vetHistoryCard:     { backgroundColor: C.white, borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, shadowColor: C.primary, shadowOpacity: 0.06, shadowOffset: { width: 0, height: 3 }, shadowRadius: 8, elevation: 2 },
  vetHistoryDateBadge:{ backgroundColor: C.primaryLight, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, alignItems: 'center', minWidth: 72 },
  vetHistoryDateText: { color: C.primary, fontWeight: '700', fontSize: 12 },
  vetHistoryReason:   { color: C.dark, fontWeight: '800', fontSize: 15 },
  vetHistoryMeta:     { color: C.textLight, fontSize: 12, fontWeight: '500' },
  historyDetailBox:   { borderRadius: 12, backgroundColor: C.surface, padding: 12 },
  historyDetailText:  { color: C.dark, fontWeight: '700', fontSize: 14 },

  // ─── Vaccines ──────────────────────────────────────────────────────────────
  vaccineCard:        { backgroundColor: C.white, borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, shadowColor: C.primary, shadowOpacity: 0.06, shadowOffset: { width: 0, height: 3 }, shadowRadius: 8, elevation: 2, overflow: 'hidden' },
  vaccineStatusBar:   { width: 4, alignSelf: 'stretch', borderRadius: 4, minHeight: 40 },
  vaccineCardName:    { fontSize: 15, fontWeight: '800', color: C.dark, flex: 1 },
  vaccineBadge:       { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3 },
  vaccineBadgeText:   { fontSize: 11, fontWeight: '700' },
  vaccineCardDate:    { fontSize: 13, color: C.textLight, fontWeight: '500' },
  vaccineCardMeta:    { fontSize: 12, color: C.textMuted, fontWeight: '500' },

  // ─── Misc ──────────────────────────────────────────────────────────────────
  listCard:    { backgroundColor: C.white, borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 14, shadowColor: C.primary, shadowOpacity: 0.06, shadowOffset: { width: 0, height: 4 }, shadowRadius: 10, elevation: 2 },
  cardTitle:   { fontSize: 17, fontWeight: '800', color: C.dark },
  cardSubtitle:{ color: C.textLight, fontSize: 14, marginTop: 2, fontWeight: '500' },
  importantNote: { color: '#92400E', fontWeight: '700', fontSize: 13 },
  detailName:  { fontSize: 24, fontWeight: '800', color: C.dark },

  // ─── Lost Pet Map ──────────────────────────────────────────────────────────
  lostMapTip: {
    backgroundColor: C.primaryLight,
    borderRadius: 14,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: C.primary,
  },
  lostMapTipText: { color: C.primaryDark, fontWeight: '600', fontSize: 13, lineHeight: 18 },
  lostMapWrap: {
    height: 320,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: C.dark,
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
  },
  lostRadiusRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  lostRadiusBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: C.border,
    alignItems: 'center',
    backgroundColor: C.white,
  },
  lostRadiusBtnActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  lostRadiusBtnText: { fontWeight: '700', fontSize: 13, color: C.textLight },
  lostRadiusBtnTextActive: { color: C.white },

  // ─── Dashboard Home ────────────────────────────────────────────────────────
  homeTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingBottom: 8,
  },
  homeTopBarLogo: {
    fontSize: 20,
    fontWeight: '900',
    color: C.primary,
    letterSpacing: -0.5,
  },
  homeAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeAvatarText: {
    fontSize: 14,
    fontWeight: '800',
    color: C.primary,
  },
  homeGreeting: {
    paddingVertical: 12,
    paddingHorizontal: 4,
    gap: 4,
  },
  homeGreetingName: {
    fontSize: 28,
    fontWeight: '900',
    color: C.dark,
    letterSpacing: -0.5,
  },
  homeGreetingMeta: {
    fontSize: 14,
    color: C.textLight,
    fontWeight: '500',
  },
  homeLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingBottom: 8,
  },
  homeLogoImg: {
    width: 52,
    height: 52,
    borderRadius: 14,
  },
  homeLogoTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: C.dark,
    letterSpacing: -0.5,
  },
  homeLogoSub: {
    fontSize: 13,
    color: C.textLight,
    fontWeight: '500',
    marginTop: 1,
  },
  dashCardIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashCardIconEmoji: {
    fontSize: 22,
  },
  nearbyAlertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 4,
    borderLeftColor: C.warning,
    gap: 4,
  },
  nearbyAlertDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: C.warning,
    marginRight: 6,
  },
  nearbyAlertTitle: { flex: 1, color: '#92400E', fontWeight: '700', fontSize: 13 },
  nearbyAlertArrow: { color: '#B45309', fontWeight: '800', fontSize: 18 },

  dashCard: {
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  dashCardAccent: {
    width: 4,
    height: 36,
    borderRadius: 2,
  },
  dashCardArrow: { fontSize: 22, color: C.textMuted, fontWeight: '300' },

  dashRow: { flexDirection: 'row', gap: 12 },

  dashCardFull: {
    backgroundColor: C.white,
    borderRadius: 18,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderTopWidth: 3,
    shadowColor: C.primary,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 2,
  },
  dashCardHalf: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: 18,
    padding: 16,
    gap: 4,
    borderTopWidth: 3,
    shadowColor: C.primary,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 2,
  },
  dashCardIcon:  { fontSize: 28 },
  dashCardTitle: { fontSize: 15, fontWeight: '800', color: C.dark },
  dashCardHint:  { fontSize: 12, color: C.textLight, fontWeight: '500' },

  // ─── Filtros ───────────────────────────────────────────────────────────────
  filterChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: C.border,
    backgroundColor: C.white,
  },
  filterChipActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  filterChipText:       { fontSize: 13, fontWeight: '700', color: C.textLight },
  filterChipTextActive: { color: C.white },

  // ─── Invite badge ───────────────────────────────────────────────────────────
  inviteBadge: {
    backgroundColor: C.accent,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 5,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: 4,
  },
  inviteBadgeText: { color: C.white, fontSize: 12, fontWeight: '800' as const },
});
