export const C = {
  primary:       '#0ABFA3',
  primaryDark:   '#07897A',
  primaryLight:  '#E0FAF6',
  accent:        '#FF8C42',
  accentLight:   '#FFF3EB',
  success:       '#059669',
  successLight:  '#ECFDF5',
  warning:       '#F59E0B',
  warningLight:  '#FFFBEB',
  danger:        '#EF4444',
  dangerLight:   '#FEF2F2',
  dark:          '#12103A',
  text:          '#12103A',
  textLight:     '#4A8C86',
  textMuted:     '#7ABFB8',
  border:        '#D6F5F0',
  surface:       '#F0FDFB',
  bg:            '#F0FDFB',
  white:         '#FFFFFF',
};
