export const C = {
  primary:       '#6C47FF',
  primaryLight:  '#EDE9FE',
  primaryDark:   '#4C1D95',
  accent:        '#FF6B6B',
  accentLight:   '#FFF1F2',
  success:       '#059669',
  successLight:  '#ECFDF5',
  warning:       '#F59E0B',
  warningLight:  '#FFFBEB',
  danger:        '#EF4444',
  dangerLight:   '#FEF2F2',
  dark:          '#1E1B4B',
  text:          '#374151',
  textLight:     '#6B7280',
  textMuted:     '#9CA3AF',
  border:        '#E5E7EB',
  surface:       '#F9FAFB',
  bg:            '#F5F3FF',
  white:         '#FFFFFF',
};
