export const COMUNAS_CHILE = [
  'Alhué','Alto Hospicio','Alto Biobío','Ancud','Andacollo','Angol','Antofagasta','Antuco','Arauco',
  'Arica','Aysén','Buin','Bulnes','Cabo de Hornos','Calama','Caldera','Calera','Calbuco','Cañete',
  'Carahue','Cartagena','Casablanca','Castro','Catemu','Cauquenes','Chaitén','Chañaral','Chépica',
  'Chiguayante','Chile Chico','Chillán','Chillán Viejo','Chimbarongo','Cholchol','Chonchi','Cisnes',
  'Cobquecura','Cochamó','Coihaique','Coinco','Colbún','Colchagua','Collipulli','Coltauco','Combarbalá',
  'Concepción','Conchalí','Constitución','Contulmo','Copiapó','Coquimbo','Coronel','Corral',
  'Cunco','Curacautín','Curacaví','Curanilahue','Curepto','Curicó','Dalcahue','Diego de Almagro',
  'Doñihue','El Bosque','El Carmen','El Monte','El Quisco','El Tabo','Empedrado','Ercilla',
  'Florida','Freirina','Fresia','Frutillar','Futaleufu','Futaleufú','Galvarino','General Lagos',
  'Graneros','Guaitecas','Hijuelas','Hualaihué','Hualañé','Hualpén','Huara','Huasco','Illapel',
  'Independencia','Iquique','Juan Fernández','La Cisterna','La Cruz','La Estrella','La Florida',
  'La Granja','La Higuera','La Ligua','La Pintana','La Reina','La Serena','La Unión','Lago Ranco',
  'Lago Verde','Laguna Blanca','Laja','Lampa','Lanco','Las Condes','Lautaro','Lebu','Licantén',
  'Limache','Linares','Lo Barnechea','Lo Espejo','Lo Prado','Lolol','Loncoche','Longaví','Lonquimay',
  'Los Andes','Los Álamos','Los Lagos','Los Muermos','Los Sauces','Los Vilos','Lota','Lumaco',
  'Macul','Maipú','Malloa','Mariquina','Maule','Mejillones','Melipeuco','Melipilla','Molina',
  'Monte Patria','Mostazal','Mulchén','Nacimiento','Nancagua','Natales','Navidad','Negrete',
  'Ninhue','Nogales','Nueva Imperial','Ñiquén','Ñuñoa','O\'Higgins','Olivar','Olmué','Osorno',
  'Ovalle','Padre Hurtado','Padre Las Casas','Paillaco','Paine','Palena','Palmilla','Panguipulli',
  'Parral','Pedro Aguirre Cerda','Pelarco','Pelluhue','Pemuco','Peñaflor','Peñalolén','Peralillo',
  'Perquenco','Petorca','Peumo','Pica','Pichidegua','Pichilemu','Pilmahue','Pinto','Pirque',
  'Pitrufquén','Placilla','Portezuelo','Porvenir','Pozo Almonte','Primavera','Providencia',
  'Puchuncaví','Pucón','Pudahuel','Puente Alto','Puerto Montt','Puerto Natales','Puerto Octay',
  'Puerto Varas','Punta Arenas','Purén','Purranque','Puyehue','Queilén','Quemchi','Quilaco',
  'Quilicura','Quilleco','Quillón','Quillota','Quilpué','Quinchao','Quinta de Tilcoco','Quinta Normal',
  'Quintero','Quirihue','Rancagua','Rauco','Recoleta','Renaico','Renca','Rengo','Requínoa',
  'Retiro','Río Bueno','Río Claro','Río Hurtado','Río Ibáñez','Río Negro','Río Vergara',
  'Romeral','Saavedra','San Antonio','San Bernardo','San Carlos','San Clemente','San Esteban',
  'San Fabián','San Felipe','San Fernando','San Gregorio','San Ignacio','San Javier',
  'San José de Maipo','San Juan de la Costa','San Miguel','San Nicolás','San Pablo','San Pedro',
  'San Pedro de Atacama','San Pedro de la Paz','San Rafael','San Ramón','San Rosendo',
  'San Vicente','Santa Bárbara','Santa Cruz','Santa Juana','Santa María','Santiago',
  'Santo Domingo','Sierra Gorda','Talca','Talcahuano','Taltal','Temuco','Teno','Tierra Amarilla',
  'Timaukel','Tirúa','Tocopilla','Toltén','Tomé','Torres del Paine','Tortel','Traiguén',
  'Trehuaco','Tucapel','Valdivia','Vallenar','Valparaíso','Victoria','Vicuña','Vilcún',
  'Villa Alegre','Villa Alemana','Villarrica','Viña del Mar','Vitacura','Yerbas Buenas','Yumbel','Zapallar'
].sort();
